### PR TITLE
Bugfix, minor documentation update, and a build of PyOPL for Linux x86_x64

### PR DESCRIPTION
**Pull request by Wohlstand**

### CODE REVIEW

**Comment by Wohlstand** [comment]
BTW, window centering should know about multi-monitor, lol:

**Comment by Wohlstand** [comment]
Also, maybe remember last window position in settings then?

**Comment by Wohlstand** [comment]
Also, this assert looks odd :thinking: 
[Fox fantasy - v2 - finger.mid.zip](https://github.com/adambiser/imf-creator/files/4058853/Fox.fantasy.-.v2.-.finger.mid.zip) (try to open this MIDI file)
Снимок экрана от 2020-01-14 14-25-43

**Comment by adambiser** [comment]
The issue is that there is a circular dependency that didn't cause an error in Python 3.7 on Windows but did in Python 3.5 on Linux.  I'd prefer not having to call the init method explicitly, if possible.

TKinter is apparently not multi-monitor aware, but there is something that might work.  Will post shortly.  Saving window position is a good idea.  Just hadn't got there yet.  A lot of TODOs.

That assert is that _in_rpn_data should either be None or True.  I'll have to take a look at your MIDI file to see what it does.  I had assumed that RPN and NRPN data wouldn't be interwoven.

**Comment by adambiser** [comment]
How did you run this with Python 3.5?  This code uses f-strings which aren't introduced until 3.6.

**Comment by Wohlstand** [comment]
> The issue is that there is a circular dependency that didn't cause an error in Python 3.7

Looks like a bug of older python, and the thing I made is a workaround for it. Yeah, 3.5 is not so old as 3.4 that may appear on some rare case. 3.5 and 3.6 are most common as I see. So, it's better to support slightly older versions are popular. Enforcing newer python version makes the harder work to bootstrap it: wille on Ubuntu/LinuxMint it's possible to install "python3.7" and manual install of missing modules, it's a pain when you need to add extra packages repository to get newer python, or even compile it from sources ever. Even on Windows are existing older python installations that aren't updated for a while. Anyway, I agree that instead of my workaround would be some better solution that should work on Python 3.5 also.

Yeah, I have tried to google about multi-monitor on Tkinter and I have found only two things:
- an ugly workaround that didn't worked at me, I tested it.
- using of a new dependency library that is installable via pip.

I may guess, here is just a glitch in the logic that cause the assert be triggered.

I'll try to check some more after sleep. At my timezone is 3:35 am (utc+3).

**Comment by adambiser** [comment]
I can duplicate the "AttributeError: module 'imfcreator' has no attribute 'instruments'" error with 3.6, but it doesn't run with 3.5 due to f-strings.

Python 2.7 and 3.4 are in end-of-life.  3.5 will be end-of-life in September.  I'm perfectly happy restricting the minimum version to 3.6 for this project.  I believe 3.6.8 is the default version for Ubuntu 18.04.

**Comment by adambiser** [comment]
I didn't find another way around this.  Merged.

**Comment by Wohlstand** [comment]
> I believe 3.6.8 is the default version for Ubuntu 18.04.

I use Linux Mint 19.3 which is based on Ubuntu 18.3, and it has Python 3.6.9 now, so, yeah.

**Comment by adambiser** [comment]
Fox fantasy - v2 - finger.mid should play as of latest python3 commit.

**Comment by Wohlstand** [comment]
> How did you run this with Python 3.5? This code uses f-strings which aren't introduced until 3.6.

No, it's my missguess because of PuCharm that said "its Python 3.5", but in fact I ran Python 3.6.9.
